version: "3.2"
services:
  nodejs:
    build: 
      context: .
    restart: always
    image: amakundu/nodejs-mysql-app
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mysql-app
      - MYSQL_USER=user_db
      - MYSQL_PASS=password
      - MYSQL_DB=desafiobo_db
    volumes:
      - ./:/var/www/html/
    ports:
      - "30003:8005"
    container_name: nodejs-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user_db
      - MYSQL_PASSWORD=password 
      - MYSQL_DATABASE=desafiobo_db
    container_name: mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: phpmyadmin-app
networks:
  frontend:
  backend: